// flow-typed signature: 2b786dc542857e323d1bf28a60612fc0
// flow-typed version: <<STUB>>/@aspnet/signalr_v^1.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@aspnet/signalr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@aspnet/signalr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@aspnet/signalr/dist/browser/signalr' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/browser/signalr.min' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/AbortController' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/browser-index' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/Errors' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/HandshakeProtocol' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/HttpClient' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/HttpConnection' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/HubConnection' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/HubConnectionBuilder' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/IConnection' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/IHttpConnectionOptions' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/IHubProtocol' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/ILogger' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/index' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/ITransport' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/JsonHubProtocol' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/Loggers' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/LongPollingTransport' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/ServerSentEventsTransport' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/Stream' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/TextMessageFormat' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/Utils' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/cjs/WebSocketTransport' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/AbortController' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/browser-index' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/Errors' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/HandshakeProtocol' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/HttpClient' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/HttpConnection' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/HubConnection' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/HubConnectionBuilder' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/IConnection' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/IHttpConnectionOptions' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/IHubProtocol' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/ILogger' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/index' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/ITransport' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/JsonHubProtocol' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/Loggers' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/LongPollingTransport' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/ServerSentEventsTransport' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/Stream' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/TextMessageFormat' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/Utils' {
  declare module.exports: any;
}

declare module '@aspnet/signalr/dist/esm/WebSocketTransport' {
  declare module.exports: any;
}

// Filename aliases
declare module '@aspnet/signalr/dist/browser/signalr.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/browser/signalr'>;
}
declare module '@aspnet/signalr/dist/browser/signalr.min.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/browser/signalr.min'>;
}
declare module '@aspnet/signalr/dist/cjs/AbortController.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/AbortController'>;
}
declare module '@aspnet/signalr/dist/cjs/browser-index.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/browser-index'>;
}
declare module '@aspnet/signalr/dist/cjs/Errors.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/Errors'>;
}
declare module '@aspnet/signalr/dist/cjs/HandshakeProtocol.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/HandshakeProtocol'>;
}
declare module '@aspnet/signalr/dist/cjs/HttpClient.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/HttpClient'>;
}
declare module '@aspnet/signalr/dist/cjs/HttpConnection.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/HttpConnection'>;
}
declare module '@aspnet/signalr/dist/cjs/HubConnection.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/HubConnection'>;
}
declare module '@aspnet/signalr/dist/cjs/HubConnectionBuilder.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/HubConnectionBuilder'>;
}
declare module '@aspnet/signalr/dist/cjs/IConnection.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/IConnection'>;
}
declare module '@aspnet/signalr/dist/cjs/IHttpConnectionOptions.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/IHttpConnectionOptions'>;
}
declare module '@aspnet/signalr/dist/cjs/IHubProtocol.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/IHubProtocol'>;
}
declare module '@aspnet/signalr/dist/cjs/ILogger.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/ILogger'>;
}
declare module '@aspnet/signalr/dist/cjs/index.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/index'>;
}
declare module '@aspnet/signalr/dist/cjs/ITransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/ITransport'>;
}
declare module '@aspnet/signalr/dist/cjs/JsonHubProtocol.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/JsonHubProtocol'>;
}
declare module '@aspnet/signalr/dist/cjs/Loggers.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/Loggers'>;
}
declare module '@aspnet/signalr/dist/cjs/LongPollingTransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/LongPollingTransport'>;
}
declare module '@aspnet/signalr/dist/cjs/ServerSentEventsTransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/ServerSentEventsTransport'>;
}
declare module '@aspnet/signalr/dist/cjs/Stream.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/Stream'>;
}
declare module '@aspnet/signalr/dist/cjs/TextMessageFormat.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/TextMessageFormat'>;
}
declare module '@aspnet/signalr/dist/cjs/Utils.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/Utils'>;
}
declare module '@aspnet/signalr/dist/cjs/WebSocketTransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/cjs/WebSocketTransport'>;
}
declare module '@aspnet/signalr/dist/esm/AbortController.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/AbortController'>;
}
declare module '@aspnet/signalr/dist/esm/browser-index.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/browser-index'>;
}
declare module '@aspnet/signalr/dist/esm/Errors.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/Errors'>;
}
declare module '@aspnet/signalr/dist/esm/HandshakeProtocol.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/HandshakeProtocol'>;
}
declare module '@aspnet/signalr/dist/esm/HttpClient.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/HttpClient'>;
}
declare module '@aspnet/signalr/dist/esm/HttpConnection.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/HttpConnection'>;
}
declare module '@aspnet/signalr/dist/esm/HubConnection.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/HubConnection'>;
}
declare module '@aspnet/signalr/dist/esm/HubConnectionBuilder.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/HubConnectionBuilder'>;
}
declare module '@aspnet/signalr/dist/esm/IConnection.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/IConnection'>;
}
declare module '@aspnet/signalr/dist/esm/IHttpConnectionOptions.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/IHttpConnectionOptions'>;
}
declare module '@aspnet/signalr/dist/esm/IHubProtocol.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/IHubProtocol'>;
}
declare module '@aspnet/signalr/dist/esm/ILogger.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/ILogger'>;
}
declare module '@aspnet/signalr/dist/esm/index.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/index'>;
}
declare module '@aspnet/signalr/dist/esm/ITransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/ITransport'>;
}
declare module '@aspnet/signalr/dist/esm/JsonHubProtocol.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/JsonHubProtocol'>;
}
declare module '@aspnet/signalr/dist/esm/Loggers.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/Loggers'>;
}
declare module '@aspnet/signalr/dist/esm/LongPollingTransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/LongPollingTransport'>;
}
declare module '@aspnet/signalr/dist/esm/ServerSentEventsTransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/ServerSentEventsTransport'>;
}
declare module '@aspnet/signalr/dist/esm/Stream.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/Stream'>;
}
declare module '@aspnet/signalr/dist/esm/TextMessageFormat.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/TextMessageFormat'>;
}
declare module '@aspnet/signalr/dist/esm/Utils.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/Utils'>;
}
declare module '@aspnet/signalr/dist/esm/WebSocketTransport.js' {
  declare module.exports: $Exports<'@aspnet/signalr/dist/esm/WebSocketTransport'>;
}
